name: Build

on: push

jobs:
  build:
    runs-on: windows-laster

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-doth
      - name: maine
        run: maine

      - name: Build application
        run: make
